services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:17
    env_file:
      - .env
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB}
    ports:
      - "127.0.0.1:5432:5432"

  migrations:
    image: ${IMAGE_HUB__URL:-ghcr.io}/${IMAGE_HUB__REPO}/${APP__NAME}:${GIT__IMAGE_TAG:-main}
    env_file:
      - .env
    environment:
      POSTGRES__HOST: postgres
    command: ["uv", "run", "alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    init: true

  app:
    image: ${IMAGE_HUB__URL:-ghcr.io}/${IMAGE_HUB__REPO}/${APP__NAME}:${GIT__IMAGE_TAG:-main}
    env_file:
      - .env
    environment:
      POSTGRES__HOST: postgres
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    init: true
    stop_grace_period: 20s

volumes:
  postgres_vol:
